# 设置固定版本号
$tag = "1.0.0"  # 固定版本号
$revision = "1.0.0-00001"  # 固定修订版本（你可以根据需要修改）

# 生成 GitVersion.cs 文件
$text = @"
    // This file is generated by update-version.ps1 
    
    using System.Reflection;
    
    [assembly: AssemblyVersion("$tag")]
    [assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8

# 更新 QuickLook.Plugin.Metadata.config 配置文件中的版本号
$xml = [xml](Get-Content $PSScriptRoot\..\QuickLook.Plugin.Metadata.Base.config)
$xml.Metadata.Version="$revision"
$xml.Save("$PSScriptRoot\..\QuickLook.Plugin.Metadata.config")
