name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup NuGet
      run: nuget restore QuickLook.Plugin.OfficeViewer-Native.sln

    - name: Build the project
      run: msbuild QuickLook.Plugin.OfficeViewer-Native.sln /p:Configuration=Release

    - name: Ensure bin\Release directory exists
      run: |
        if (-Not (Test-Path "D:\a\QuickLook.Plugin.OfficeViewer-Native\bin\Release")) {
          Write-Host "Creating bin\Release directory..."
          New-Item -ItemType Directory -Path "D:\a\QuickLook.Plugin.OfficeViewer-Native\bin\Release"
        }

    - name: Run pack-zip.ps1 script
      run: powershell -ExecutionPolicy Bypass -File ./Scripts/pack-zip.ps1
